int _putchar(char);
void reset_to_98(int);
int _strlen(char);
void swap_int(int, int);
void _puts(char);
void print_rev(char);
void rev_string(char);
void puts2(char);
void puts_half(char);
void print_array(int, int);
char *_strcpy(char, char);
